name: Default Pipeline

on:
  push:
    branches:
      - '**' # Runs on all branches
      - '!develop' # Exclude develop branch
      - '!main' # Exclude main branch

jobs:
  test-build:
    # Job to get dependencies and test build on non-develop/main branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build
